(cl:defpackage miro2_msg-msg
  (:use )
  (:export
   "<ADJUST>"
   "ADJUST"
   "<AFFECT>"
   "AFFECT"
   "<AFFECT_ADJUST>"
   "AFFECT_ADJUST"
   "<ANIMAL_ADJUST>"
   "ANIMAL_ADJUST"
   "<ANIMAL_STATE>"
   "ANIMAL_STATE"
   "<FUNNEL_WEB>"
   "FUNNEL_WEB"
   "<OBJECT_BALL>"
   "OBJECT_BALL"
   "<OBJECT_FACE>"
   "OBJECT_FACE"
   "<OBJECT_TAG>"
   "OBJECT_TAG"
   "<OBJECTS>"
   "OBJECTS"
   "<PRIORITY_PEAK>"
   "PRIORITY_PEAK"
   "<PUSH>"
   "PUSH"
   "<SENSORS_PACKAGE>"
   "SENSORS_PACKAGE"
   "<SLEEP>"
   "SLEEP"
   "<SLEEP_ADJUST>"
   "SLEEP_ADJUST"
   "<VOICE_STATE>"
   "VOICE_STATE"
  ))

