(cl:in-package miro2_msg-msg)
(cl:export '(HEADER-VAL
          HEADER
          BATTERY-VAL
          BATTERY
          CLIFF-VAL
          CLIFF
          DIP-VAL
          DIP
          FLAGS-VAL
          FLAGS
          IMU_HEAD-VAL
          IMU_HEAD
          IMU_BODY-VAL
          IMU_BODY
          KINEMATIC_JOINTS-VAL
          KINEMATIC_JOINTS
          LIGHT-VAL
          LIGHT
          ODOM-VAL
          ODOM
          SONAR-VAL
          SONAR
          STREAM-VAL
          STREAM
          TOUCH_BODY-VAL
          TOUCH_BODY
          TOUCH_HEAD-VAL
          TOUCH_HEAD
          WHEEL_SPEED_CMD-VAL
          WHEEL_SPEED_CMD
          WHEEL_SPEED_BACK_EMF-VAL
          WHEEL_SPEED_BACK_EMF
          WHEEL_SPEED_OPTO-VAL
          WHEEL_SPEED_OPTO
          WHEEL_EFFORT_PWM-VAL
          WHEEL_EFFORT_PWM
          BODY_POSE-VAL
          BODY_POSE
))